"""add playerstate table

Revision ID: 4446fe050ef7
Revises: c300ce029dad
Create Date: 2026-08-16 00:53:46.050372

Part5 永続統合ワールド化（P3-01）: PlayerState を追加のみ行う。MissionState は
このリビジョンでは drop しない（API/WS 層がまだ MissionState を読み書きしている
ため）。missionstate テーブルの drop は、API/WS 層を PlayerState に切り替える
カットオーバー（P3-10/P3-11）完了後に別 Alembic リビジョンとして行う。
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4446fe050ef7'
down_revision: Union[str, Sequence[str], None] = 'c300ce029dad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playerstate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playerstate_user_id'), 'playerstate', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_playerstate_user_id'), table_name='playerstate')
    op.drop_table('playerstate')
    # ### end Alembic commands ###
