"""drop missionstate table

Revision ID: 63217880f0a0
Revises: 4446fe050ef7
Create Date: 2026-09-13 19:53:07.838488

Phase F（tests/test_mission*.py の統合ワールド state への移行完了）に伴い、
API/WS 層がもう読み書きしない旧 MissionState（Mission 別 state。user_id +
mission_id 単位）のテーブルを廃止する。PlayerState（永続統合ワールド）のみが
現役になる。
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63217880f0a0'
down_revision: Union[str, Sequence[str], None] = '4446fe050ef7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_missionstate_mission_id'), table_name='missionstate')
    op.drop_index(op.f('ix_missionstate_user_id'), table_name='missionstate')
    op.drop_table('missionstate')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('missionstate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'mission_id', name='uq_user_mission')
    )
    op.create_index(op.f('ix_missionstate_mission_id'), 'missionstate', ['mission_id'], unique=False)
    op.create_index(op.f('ix_missionstate_user_id'), 'missionstate', ['user_id'], unique=False)
    # ### end Alembic commands ###
